### ISSUE TITLE
Please Forgive Angelo For Bad Code Quality

### ISSUE THREAD

**Issue by ndneighbor** [uptous2020/site#6]
Small Quality of Life Changes To Be Done

- [x] Navbar Refactor
- [x] Footer Refactor
- [x] Team Page Refactor
- [ ] Contact Form Embedded Into Site Rather Than iFrame

**Comment by erz0r** [comment]
i forgive angelo for bad code quality

**Comment by ndneighbor** [comment]
Code QoL Done and Merged, nice job team
